### ISSUE TITLE
Implement Nav bar for User sign in, sign out, edit registration

### ISSUE THREAD

**Issue by sleekramer** [sleekramer/Injury-Forum#3]
![scan 2](https://cloud.githubusercontent.com/assets/15223881/11856759/10f250f0-a421-11e5-9e7d-1595ad38325c.jpeg)
- Create a navbar partial to be used in the application.html file that will indicate to a user whether they are signed in.
- If a user is already signed in, links to their edit_registration_path and their destroy_session_path should be displayed
- If a user is not signed in, links_to "Sign In" and "Sign Up" should be displayed

**Comment by beaugaines** [comment]
nice wireframe!
